# file: .github/workflows/hexlet-ci-app.yml
name: hexlet-ci-app
# on – определяет события, которые запускают воркфлоу
on: push
# Пример для проекта на Node.js
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Устанавливаем Node.js
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      # Ставим зависимости
      - run: make install
      # Устанавливаем проект
      - run: make setup
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # Запускаем тесты
      - run: make test
      # Запускаем линтер
      - run: make lint
