# Пример для проекта на Node.js
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Устанавливаем Node.js
      - uses: actions/setup-node@v1
      # Ставим зависимости
      - run: npm install
      # Устанавливаем проект
      - run: make setup
      # Запускаем проект
      - run: make start
      # Запускаем тесты
      - run: make test
      # Запускаем линтер
      - run: make lint
